name: TrainTestModel Workflow

on: [push]

jobs:  
  pre-test-model:
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install dependencies for pre-testing
      run: pip install scikit-learn pandas numpy  # mlflow 
    - name: Run Model Pre-Tests
      run: pytest tests/model_pre_tests.py

  train-model:
    needs: pre-test-model
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install dependencies for training
      run: pip install mlflow  #scikit-learn pandas numpy
    - name: Train model using MLflow
      run: python train.py
  
  test-model:
    needs: train-model
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install dependencies for testing
      run: pip install langfuse # scikit-learn pandas numpy mlflow 
    - name: Test model using MLflow, Langfuse
      run: python model_tests.py

  # Оставляем сборку контейнеров закомментированными, так как они пока не используются    
    # - name: Build Docker image
    #   run: docker build -t my-image .